baseURL: 'https://angelagilhotra.com'
title: Angela Gilhotra
paginate: 999
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpored: false
enableGitInfo: true

minify:
  disableXML: true
  minifyOutput: true

params:
  ShowReadingTime: true
  ShowShareButtons: true
  comments: true
  defaultTheme: auto
  disableThemeToggle : false
  disableSpecial1stPost : false

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Hi there üëã, I'm Angela
    imageUrl: "https://gateway.pinata.cloud/ipfs/QmZHqLjjucWgUVP8ewb7kCTPSyV9VPUBXiXFFS5KR5fruH"
    imageTitle: me
    buttons:
      - name: "What I'm upto"
        url: tags
      - name: 'About'
        url: about-me

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: 'https://twitter.com/angelagilhotra'
    - name: github
      url: 'https://github.com/nglglhtr'
    - name: email
      url: 'mailto:angelagilhotra@gmail.com'

  analytics:
    google:
      SiteVerificationTag: "GTM-KFVMJGP"

menu:
  main:
    - name: archive
      url: /archives/
    - name: üßò‚Äç‚ôÇÔ∏è
      url: /music

taxonomies:
  category: categories
  tag: tags
